In [1]:
import tensorflow as tf

2024-04-23 14:07:23.473312: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: SSE4.1 SSE4.2 AVX AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


## 1. create tensors

In [8]:
# scalar, rank-0 tensor
x = tf.constant(4)
print(x)

tf.Tensor(4, shape=(), dtype=int32)


In [9]:
x = tf.constant(4, shape=(1,1), dtype=tf.float32)
print(x)

tf.Tensor([[4.]], shape=(1, 1), dtype=float32)


In [10]:
# vector, rank-1
x = tf.constant([1,2,3])
print(x)

tf.Tensor([1 2 3], shape=(3,), dtype=int32)


In [11]:
# matrix, rank-2
x = tf.constant([[1,2,3], [4,5,6]])
print(x)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [12]:
x = tf.ones((3,3))
print(x)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float32)


In [13]:
x = tf.zeros((3,3))
print(x)

tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]], shape=(3, 3), dtype=float32)


In [14]:
x = tf.eye(3)
print(x)

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)


In [15]:
x = tf.random.normal((3,3), mean=0, stddev=1)
print(x)

tf.Tensor(
[[-0.19592357  0.71280575  0.20270513]
 [ 0.19291319  0.709191    0.69199914]
 [ 0.22565857 -1.2233511  -0.43106076]], shape=(3, 3), dtype=float32)


In [16]:
x = tf.random.uniform((3,3), minval=0, maxval=1)
print(x)

tf.Tensor(
[[0.56178117 0.07077396 0.17482638]
 [0.09750521 0.18293726 0.93476677]
 [0.2810576  0.71753883 0.04992294]], shape=(3, 3), dtype=float32)


In [18]:
x = tf.range(10)
print(x)

tf.Tensor([0 1 2 3 4 5 6 7 8 9], shape=(10,), dtype=int32)


## 2. cast

In [19]:
x = tf.cast(x, dtype=tf.float32)
print(x)

tf.Tensor([0. 1. 2. 3. 4. 5. 6. 7. 8. 9.], shape=(10,), dtype=float32)


## 3. operations

In [20]:
# elementwise

x = tf.constant([1,2,3])
y = tf.constant([4,5,6])

In [23]:
z = tf.add(x,y)
z

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([5, 7, 9], dtype=int32)>

In [24]:
z = tf.subtract(x,y)
z

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([-3, -3, -3], dtype=int32)>

In [25]:
z = tf.divide(x,y)
z

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([0.25, 0.4 , 0.5 ])>

In [28]:
z = tf.multiply(x,y)
z

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 4, 10, 18], dtype=int32)>

In [31]:
# dot product
x = tf.constant([1,2,3])
y = tf.constant([4,5,6])

z = tf.tensordot(x,y, axes=1)
print(z)

# sum of all multiplication

tf.Tensor(32, shape=(), dtype=int32)


In [33]:
# elementwise exponentiate
z = x ** 2
print(z)

tf.Tensor([1 4 9], shape=(3,), dtype=int32)


In [42]:
# matrix multiplication

x = tf.random.normal((2,2))
y = tf.random.normal((2,2))

In [43]:
x

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0.06671553, 0.00995909],
       [0.86943346, 1.7938937 ]], dtype=float32)>

In [44]:
y

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-1.0974464,  1.0687774],
       [-1.4200546,  1.4370403]], dtype=float32)>

In [45]:
tf.matmul(x,y)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.08735917,  0.08561566],
       [-3.5015836 ,  3.5071285 ]], dtype=float32)>

## 4. indexing, slicing

In [51]:
x = tf.constant([[1,2,3,4],[5,6,7,8]])

In [52]:
print(x[0])

tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)


In [54]:
print(x[:, 0])

tf.Tensor([1 5], shape=(2,), dtype=int32)


In [59]:
print(x[1, :])

tf.Tensor([5 6 7 8], shape=(4,), dtype=int32)


In [60]:
print(x[1,1])

tf.Tensor(6, shape=(), dtype=int32)


## 5. reshape

In [75]:
y = tf.ones((2,3))
y

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [90]:
x = tf.reshape(y, (3,2))
x

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.],
       [1., 1.]], dtype=float32)>

In [89]:
x = tf.reshape(y, (6))
x

<tf.Tensor: shape=(6,), dtype=float32, numpy=array([1., 1., 1., 1., 1., 1.], dtype=float32)>

In [92]:
x = tf.reshape(y, (-1,2))
x

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.],
       [1., 1.]], dtype=float32)>

## 6. numpy

In [118]:
x = tf.ones((2,3))
x

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [120]:
x = x.numpy()
x

array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [121]:
type(x)

numpy.ndarray

In [128]:
# string tensor
x = tf.constant((["Patrick"]))
x

<tf.Tensor: shape=(1,), dtype=string, numpy=array([b'Patrick'], dtype=object)>

In [129]:
x = tf.constant(["Patrick", "Max", "Mary"])
x

<tf.Tensor: shape=(3,), dtype=string, numpy=array([b'Patrick', b'Max', b'Mary'], dtype=object)>