# How to create Tensor with every elements are one in TensorFlow 2.x

In [1]:
# import tensorflow

import tensorflow as tf

2024-04-20 21:20:56.272666: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: SSE4.1 SSE4.2 AVX AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


## tf.ones()

In [17]:
ones_2dt = tf.ones((3, 2), tf.int32)
ones_2dt

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 1],
       [1, 1],
       [1, 1]], dtype=int32)>

In [20]:
ones_3dt = tf.ones((3, 2, 2), tf.int32)
ones_3dt

<tf.Tensor: shape=(3, 2, 2), dtype=int32, numpy=
array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)>

## tf.ones_like()

In [30]:
var_2dt = tf.Variable([[1,2, 3], [2,3, 3]])
var_2dt

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[1, 2, 3],
       [2, 3, 3]], dtype=int32)>

In [31]:
tf.ones_like(var_2dt)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 1, 1],
       [1, 1, 1]], dtype=int32)>

## tf.ones_intializer()

In [32]:
def ones_variable(shape, dtype, intializer):
    return tf.Variable(intializer(shape=shape, dtype=dtype))

In [33]:
ones_variable((2,2), tf.float32, tf.ones_initializer())

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[1., 1.],
       [1., 1.]], dtype=float32)>