# How To Addition/Add 2 Tensors In TensorFlow?

**tf.add() : Do Element wise Addition with x & y**

It can add list, tuple, scaler, <br>
TensorFlow variable/constant/placeholder/SparceMatrix with each other and with scaler and with list/tuple.

In [1]:
# import module
import tensorflow as tf
import numpy as np

2024-04-22 15:55:49.787707: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: SSE4.1 SSE4.2 AVX AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


## Scaler Adding

In [2]:
a = 20
b = 30

In [3]:
a+b

50

In [4]:
tf.add(a,b)

<tf.Tensor: shape=(), dtype=int32, numpy=50>

## Add 2 List

In [5]:
l1 = [4,4,5,6]
l2 = [9,8,8,1]

tf.add(l1,l2)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([13, 12, 13,  7], dtype=int32)>

## Add Tuple

In [6]:
t1 = (1,2,3)
t2 = (4,5,6)

tf.add(t1,t2)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([5, 7, 9], dtype=int32)>

## Add List/Tuple with scaler

In [7]:
l1 = [4,4,5,6]
t1 = (1,2,3,4)

tf.add(l1,t1)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 5,  6,  8, 10], dtype=int32)>

## Add 2 Numpy array

In [8]:
npa1 = np.array([1,2,3,4])
npa2 = np.array([1,2,3,4])

tf.add(npa1,npa2)

<tf.Tensor: shape=(4,), dtype=int64, numpy=array([2, 4, 6, 8])>

## Add 2 tf.ones()

In [9]:
to1 = tf.ones((3,2))
to2 = tf.ones((3,2))

tf.add(to1, to2)

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[2., 2.],
       [2., 2.],
       [2., 2.]], dtype=float32)>