# How to subtract of 2 Tensot in TensorFlow ?

#### **tf.subtract() : Do Element wise subtraction with x & y**
It can subtract list, tuple, scaler, TensorFlow variable/constant/placeholder/SparceMatrix with each other and with scaler and with list/tuple.

Note: – operator can be used to subtract 2 tensors

**Syntax: tf.subtract(x, y, name=None)**

In [1]:
import tensorflow as tf
import numpy as np

The history saving thread hit an unexpected error (OperationalError('attempt to write a readonly database')).History will not be written to the database.


2024-04-22 16:03:55.731380: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: SSE4.1 SSE4.2 AVX AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


## Scaler Subtract

In [4]:
a = 10
b = 20

tf.subtract(a,b)

<tf.Tensor: shape=(), dtype=int32, numpy=-10>

## subtract scaler with List/Tuple

In [7]:
a = 10
l1 = (10,20,30,40)
tf.subtract(l1,a)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 0, 10, 20, 30], dtype=int32)>

## substract of 2 Tuple/List with different shape

In [9]:
t1 = [1,2,3,4]
t2 = [1]

tf.subtract(t1,t2)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([0, 1, 2, 3], dtype=int32)>

## substract 2 numpy arrays

In [13]:
npa1 = np.array([2,3,4,5])
npa2 = np.array([4,6,8,10])

tf.subtract(npa2, npa1)

<tf.Tensor: shape=(4,), dtype=int64, numpy=array([2, 3, 4, 5])>

## subtract Numpy arrays with scaler

In [17]:
npa1 = np.array([0,1,2,3,4])
a = 10

tf.subtract(npa1,a)

<tf.Tensor: shape=(5,), dtype=int64, numpy=array([-10,  -9,  -8,  -7,  -6])>

## subtract Numpy arrays with single element np array

In [18]:
npa1 = np.array([1,2,3,4])
npa2 = np.array([1])

tf.subtract(npa1, npa2)

<tf.Tensor: shape=(4,), dtype=int64, numpy=array([0, 1, 2, 3])>

## subtract 2 TF Constant Tensor

In [25]:
tf_c1 = tf.constant([1,2,0])
tf_c2 = tf.constant([2,2,False])

tf.subtract(tf_c1, tf_c2)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([-1,  0,  0], dtype=int32)>

## subtract 2 TF Variable

In [29]:
tf_v1 = tf.Variable([1,2,3,4])
tf_v2 = tf.Variable([1,2,4,4])

tf.subtract(tf_v1,tf_v2)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 0,  0, -1,  0], dtype=int32)>

## subtract of 2d Scaler

In [30]:
a = [[1,2,3,4], [1,2,3,4]]
b = [[1,2,3,4], [4,3,2,1]]

tf.subtract(a,b)

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[ 0,  0,  0,  0],
       [-3, -1,  1,  3]], dtype=int32)>