# How To Multiplication/multiply of Tensors In TensorFlow?

**tf.multiply() :** Do Element wise Multiplication,

It can be multiply list, tuple, scaler,
tf variable/constant/placeholder/SparceMatrix with each other and with scaler and with list/tuple

**Note:** operator can be used to multiply 2 tensors

In [1]:
# import module
import tensorflow as tf
import numpy as np

2024-04-22 17:21:58.165739: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: SSE4.1 SSE4.2 AVX AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


## Scaler Multiply

In [2]:
a = 20
b = 30

In [3]:
a*b

600

In [5]:
tf.multiply(a,b)

<tf.Tensor: shape=(), dtype=int32, numpy=600>

## multiply 2 List

In [6]:
l1 = [4,4,5,6]
l2 = [9,8,8,1]

tf.multiply(l1,l2)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([36, 32, 40,  6], dtype=int32)>

## multiply Tuple

In [7]:
t1 = (1,2,3)
t2 = (4,5,6)

tf.multiply(t1,t2)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 4, 10, 18], dtype=int32)>

## multiply List/Tuple with scaler

In [8]:
l1 = [4,4,5,6]
t1 = (1,2,3,4)

tf.multiply(l1,t1)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 4,  8, 15, 24], dtype=int32)>

## multiply 2 Numpy array

In [9]:
npa1 = np.array([1,2,3,4])
npa2 = np.array([1,2,3,4])

tf.multiply(npa1,npa2)

<tf.Tensor: shape=(4,), dtype=int64, numpy=array([ 1,  4,  9, 16])>

## multiply 2 tf.ones()

In [12]:
to1 = tf.ones((2,2,2))
to2 = tf.ones((2,2,2))

tf.multiply(to1, to2)

<tf.Tensor: shape=(2, 2, 2), dtype=float32, numpy=
array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]], dtype=float32)>

## multiply 2d array

In [ ]:
np_2da1 = np.array([[1,2,3],[2,3,4]])
np_2da1 = np.array([[3,2,3],[2,3,4]])

