# How To Do Division/Divide Of Tensors In TensorFlow?

**tf.divide() :** Do Element wise division,
It can be divide scaler, Numpy array but not with list, tuple.
tf variable/constant/placeholder/SparceMatrix with each other and with scaler and with list/tuple

**Note :** / or // operator can be use to divide 2 tensors

In [1]:
# import module
import tensorflow as tf
import numpy as np

2024-04-22 17:41:39.608068: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: SSE4.1 SSE4.2 AVX AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


## Scaler division

In [4]:
a = 20
b = 2

In [5]:
a/b

10.0

In [6]:
tf.divide(a,b)

<tf.Tensor: shape=(), dtype=float64, numpy=10.0>

## divide 2 List

In [9]:
l1 = [3,4,2,6]
l2 = [9,8,8,12]

tf.divide(l2,l1)

<tf.Tensor: shape=(4,), dtype=float64, numpy=array([3., 2., 4., 2.])>

## divide Tuple

In [10]:
t1 = (1,2,3)
t2 = (4,5,6)

tf.divide(t1,t2)

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([0.25, 0.4 , 0.5 ])>

## divide List/Tuple with scaler

In [12]:
l1 = [9,8,8,12]
t1 = (3,4,2,6)

tf.divide(l1,t1)

<tf.Tensor: shape=(4,), dtype=float64, numpy=array([3., 2., 4., 2.])>

## divide 2 Numpy array

In [14]:
npa1 = np.array([1,2,3,4])
npa2 = np.array([1,2,3,4])

tf.divide(npa1,npa2)

<tf.Tensor: shape=(4,), dtype=float64, numpy=array([1., 1., 1., 1.])>

## divide 2 tf.ones()

In [15]:
to1 = tf.ones((2,2,2))
to2 = tf.ones((2,2,2))

tf.divide(to1, to2)

<tf.Tensor: shape=(2, 2, 2), dtype=float32, numpy=
array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]], dtype=float32)>

## divide 2d array

In [18]:
np_2da1 = np.array([[1,2,3],[2,3,4]])
np_2da2 = np.array([[3,2,3],[2,3,4]])

tf.divide(np_2da1, np_2da2)

<tf.Tensor: shape=(2, 3), dtype=float64, numpy=
array([[0.33333333, 1.        , 1.        ],
       [1.        , 1.        , 1.        ]])>

In [25]:
np_2da1 // np_2da2

array([[0, 1, 1],
       [1, 1, 1]])

In [24]:
t1 = (1,2,3)
t2 = 4

tf.divide(t1,t2)

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([0.25, 0.5 , 0.75])>