## How To Calculate Square Root Of Tensors In TensorFlow?

**tf.sqrt() :** Calculate Element wise square root of numpy array and TF tensor,
It can be give sqrt of list, tuple, scaler
It allow tf variable/constant/placeholder/SparceMatrix with Specific datatype

Data Type : bfloat16, half, float32, float64, complex64, complex128.

**Note:** Don’t give ‘int’ data type, tf.sqrt() will through error

In [1]:
# import module

import tensorflow as tf
import numpy as np

2024-04-22 18:07:20.016151: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: SSE4.1 SSE4.2 AVX AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


## Square Root of Scaler

In [11]:
a = 9.0

In [12]:
tf.sqrt(a)

<tf.Tensor: shape=(), dtype=float32, numpy=3.0>

## Square root of List

In [23]:
l1 = [4.0,9.0,16.0,25.0,36.0]

tf.sqrt(l1)

<tf.Tensor: shape=(5,), dtype=float32, numpy=array([2., 3., 4., 5., 6.], dtype=float32)>

## Square Root of Tuple

In [25]:
t1 = (4.0,9.0,16.0,25.0,36.0)

tf.sqrt(t1)

<tf.Tensor: shape=(5,), dtype=float32, numpy=array([2., 3., 4., 5., 6.], dtype=float32)>

## Square Root of Numpy Array

In [27]:
npa1 = np.array([4,9,16], dtype=np.float64)

tf.sqrt(npa1)

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([2., 3., 4.])>

In [29]:
npa1.dtype

dtype('float64')

## Square Root of Tensor

In [31]:
tf.sqrt(tf.convert_to_tensor(4, dtype='float'))

<tf.Tensor: shape=(), dtype=float32, numpy=2.0>

In [34]:
tf_V = tf.Variable((4,9), dtype='float')

In [35]:
tf.sqrt(tf_V)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([2., 3.], dtype=float32)>

In [36]:
tf_2d_V = tf.Variable(([[4,9],[16,25]]), dtype='float')

In [37]:
tf.sqrt(tf_2d_V)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[2., 3.],
       [4., 5.]], dtype=float32)>