# How To Calculate Power Of Tensors In TensorFlow?

**tf.pow():** Calculate the power of one value to another, Element wise power calculation
It can be given the power of scaler, Numpy array
It allow tf variable/constant/placeholder/SparceMatrix with Specific datatype

Data Type : float16, float32, float64, int32, int64, complex64, or complex128.

**Note:** Don’t pass data in integer format, it will through error

In [1]:
# Import the Module
import tensorflow as tf
import numpy as np

2024-04-23 11:24:15.172014: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: SSE4.1 SSE4.2 AVX AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


## Power of Scaler

In [16]:
a = 2
b = 2

tf.pow(a, b)

<tf.Tensor: shape=(), dtype=int32, numpy=4>

## Power of Numpy array

In [18]:
npa1 = np.array([2,3,4], dtype=np.float64)

tf.pow(npa1, 2)

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 4.,  9., 16.])>

In [19]:
npa1 = np.array([2,3,4], dtype=np.float64)
npa2 = np.array([2,3,4], dtype=np.float64)

tf.pow(npa1, npa2)

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([  4.,  27., 256.])>

## Power of TF Constant Tensor

In [22]:
tf_c1 = tf.constant([2,2])

tf.pow(tf_c1, 2)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([4, 4], dtype=int32)>

## Power of TF Variable Tensor

In [24]:
tf_v1 = tf.Variable([2,2])

tf.pow(tf_v1, 2)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([4, 4], dtype=int32)>