# How To Get Maximum Value From Tensors In TensorFlow?

**tf.maximum() :** Returns the maximum value by comparing of x and y (i.e. x > y ? x : y) element-wise.<br>
It work with list, tuple, scaler, Numpy array<br>
tf variable/constant/placeholder/SparceMatrix with each other and with scaler and with list/tuple

In [11]:
# Import module
import tensorflow as tf
import numpy as np

## Get max value of Scaler

In [12]:
a = 15
b = 19

tf.minimum(a, b)

<tf.Tensor: shape=(), dtype=int32, numpy=19>

## Get max value of List

In [13]:
l1 = [10,15,10]
l2 = [22,8,30]

tf.minimum(l1, l2)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([22, 15, 30], dtype=int32)>

In [14]:
l1 = [10,6,10]
l2 = [7]

tf.minimum(l1, l2)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([10,  7, 10], dtype=int32)>

## Get max value of Tuple

In [15]:
t1 = (10,15,10)
t2 = (22,8,30)

tf.minimum(t1, t2)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([22, 15, 30], dtype=int32)>

In [16]:
tf.minimum(l1, l2).numpy()

array([10,  7, 10], dtype=int32)

## Get max value of Tuple/List with Scaler

In [17]:
t1 = (10,0,10)
a = 1

tf.minimum(t1, a)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([10,  1, 10], dtype=int32)>

In [18]:
l1 = [10,0,10]
a = 1

tf.minimum(l1, a)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([10,  1, 10], dtype=int32)>

## Get max value of 2 Numpy arrays

In [19]:
npa1 = np.array([10,15,10])
npa2 = np.array([22,8,30])

tf.minimum(npa1, npa2)

<tf.Tensor: shape=(3,), dtype=int64, numpy=array([22, 15, 30])>

## Get max value of 2 TF Variable 

In [21]:
tf_v1 = tf.Variable([2,2,3])
tf_v2 = tf.Variable([4,5,6])

tf.minimum(tf_v1, tf_v2)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([4, 5, 6], dtype=int32)>

## Get max value of 2 TF Constant

In [23]:
tf_c1 = tf.constant([2,4])
tf_c2 = tf.constant([4,2])

tf.minimum(tf_c1, tf_c2)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([4, 4], dtype=int32)>