# **How To Create Variable In TensorFlow 2.X Tutorial**

The **Variable()** constructor requires an initial value for the variable, which can be a Tensor of any type and shape. This initial value defines the type and shape of the variable. After construction, the type and shape of the variable are fixed. The value can be changed using one of the assign methods.

**Syntax:**


```
tf.Variable(
initial_value=None, trainable=None, validate_shape=True, caching_device=None,
name=None, variable_def=None, dtype=None, import_scope=None, constraint=None,
synchronization=tf.VariableSynchronization.AUTO,
aggregation=tf.compat.v1.VariableAggregation.NONE, shape=None
)
```

# Import TensorFlow

In [16]:
import tensorflow as tf

# Create Tensor

In [3]:
tf.Variable(1)

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=1>

In [4]:
a = tf.Variable([1, 2, 3, 4])
a

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [5]:
# Check Variable Name
a.name

'Variable:0'

In [6]:
# Check DataType of Tensor's Elements

a.dtype

tf.int32

In [7]:
# Shape of Tensor

a.shape

TensorShape([4])

In [8]:
# Check Variable Type

type(a)

tensorflow.python.ops.resource_variable_ops.ResourceVariable

# Create TF using Integer, Float, String, Bool, complex Number

In [9]:
# Integer

tf_i = tf.Variable([1])
tf_i

<tf.Variable 'Variable:0' shape=(1,) dtype=int32, numpy=array([1], dtype=int32)>

In [10]:
# String

tf_s = tf.Variable(["Hii, i'm FIne!"])
tf_s

<tf.Variable 'Variable:0' shape=(1,) dtype=string, numpy=array([b"Hii, i'm FIne!"], dtype=object)>

In [11]:
# Float

tf_f = tf.Variable([1.2])
tf_f

<tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([1.2], dtype=float32)>

In [12]:
# Complex

tf_cp = tf.Variable([3+4j])
tf_cp

<tf.Variable 'Variable:0' shape=(1,) dtype=complex128, numpy=array([3.+4.j])>

# Create TF From Constant TensorFlow Variable

In [13]:
tf_t = tf.constant([1,2,3,4])
tf_t

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [14]:
tf_variable = tf.Variable(tf_t)
tf_variable

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

# Create TF Variable with different Shape

In [15]:
tf_t = tf.Variable([[1,2], [3,4]], shape=(2,2))
tf_t

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [66]:
a

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [88]:
b = tf.reshape(a, (2, 2))

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

# Get index of Highest Value

In [19]:
b = tf.Variable([[1, 5], [3, 4]])
b

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[1, 5],
       [3, 4]], dtype=int32)>

In [20]:
tf.argmax(b)

<tf.Tensor: shape=(2,), dtype=int64, numpy=array([1, 0])>

# Viewed/Convert as a tensor

In [21]:
a

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [22]:
tf.convert_to_tensor(a)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [24]:
tf.convert_to_tensor(tf_t)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

# Change/Assign new value to tensor

In [25]:
a

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [27]:
a.assign([2,3,8,5])

<tf.Variable 'UnreadVariable' shape=(4,) dtype=int32, numpy=array([2, 3, 8, 5], dtype=int32)>

In [28]:
a

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([2, 3, 8, 5], dtype=int32)>

# Assign Variable with another Memory

In [29]:
a.assign_add([2,3,8,5])

<tf.Variable 'UnreadVariable' shape=(4,) dtype=int32, numpy=array([ 4,  6, 16, 10], dtype=int32)>

In [30]:
a

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([ 4,  6, 16, 10], dtype=int32)>