# Create Sparse Tensor using TensorFlow 2.0

### What is Sparse Tensor?

**Tensor that contain mostly zero values are called sparse tensor.**

When working with tensors that contain a lot of zero values, it is important to store them in a space- and time-efficient manner. Sparse tensors enable efficient storage and processing of tensors that contain a lot of zero values.
Sparse tensors are used extensively in encoding schemes like TF-IDF as part of data pre-processing in NLP applications and for pre-processing images with a lot of dark pixels in computer vision applications.

Currently, sparse tensors in TensorFlow are encoded using the coordinate list (COO) format.

The COO encoding for sparse tensors is comprised of:

values: A 1D tensor with shape [N] containing all nonzero values.
indices: A 2D tensor with shape [N, rank], containing the indices of the nonzero values.
dense_shape: A 1D tensor with shape [rank], specifying the shape of the tensor.

### Syntax of sparse Tensor

```tf.sparse.SparseTensor(indices, values, desne_shape)```

In [1]:
# Import TensorFlow 2.x
import tensorflow as tf

2024-04-20 19:48:48.695253: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: SSE4.1 SSE4.2 AVX AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [6]:
st1 = tf.SparseTensor(indices=[[0,2], [3,4]], values=[10,15], dense_shape=[3,10])
st1

SparseTensor(indices=tf.Tensor(
[[0 2]
 [3 4]], shape=(2, 2), dtype=int64), values=tf.Tensor([10 15], shape=(2,), dtype=int32), dense_shape=tf.Tensor([ 3 10], shape=(2,), dtype=int64))

## Create Sparse Tensor From Dense

In [8]:
import numpy as np

In [83]:
np_arrays = np.array([[1,0,0,0],
                      [0,0,0,0],
                      [0,0,2,0],
                      [0,0,0,5]])

np_arrays

array([[1, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 5]])

In [86]:
st2_fd = tf.sparse.from_dense(np_arrays)
st2_fd

SparseTensor(indices=tf.Tensor(
[[0 0]
 [2 2]
 [3 3]], shape=(3, 2), dtype=int64), values=tf.Tensor([1 2 5], shape=(3,), dtype=int64), dense_shape=tf.Tensor([4 4], shape=(2,), dtype=int64))

## Extract the values, indices & Shape of Sparse Tensor

In [89]:
# Values

st1.values

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 15], dtype=int32)>

In [96]:
# indices

st1.indices.numpy().tolist()

[[0, 2], [3, 4]]

In [99]:
st1.dense_shape.numpy().tolist()

[3, 10]

## Sparse Tensor to Dense Tensor

In [101]:
dt_fst = tf.sparse.to_dense(st2_fd)
dt_fst

<tf.Tensor: shape=(4, 4), dtype=int64, numpy=
array([[1, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 5]])>

In [104]:
# Convert Dense Tensor into numpy a

dt_fst.numpy()

array([[1, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 5]])