# How to create Tensor with every elements are zero in TensorFlow 2.x

In [1]:
# import tensorflow

import tensorflow as tf

2024-04-20 22:30:13.961742: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: SSE4.1 SSE4.2 AVX AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


## tf.zeros()

In [12]:
zeros_2dt = tf.zeros((3,4))
zeros_2dt

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

In [26]:
zeros_3dt = tf.zeros((2,2,3,4), dtype=tf.int8)
zeros_3dt

<tf.Tensor: shape=(2, 2, 3, 4), dtype=int8, numpy=
array([[[[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]],

        [[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]]],


       [[[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]],

        [[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]]]], dtype=int8)>

In [27]:
zeros_3dt.shape

TensorShape([2, 2, 3, 4])

In [28]:
zeros_3dt.dtype

tf.int8

In [29]:
zeros_3dt.numpy()

array([[[[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]],

        [[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]]],


       [[[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]],

        [[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]]]], dtype=int8)

In [30]:
zeros_3dt.numpy().tolist()

[[[[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]],
  [[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]]],
 [[[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]],
  [[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]]]]

## tf.zeros_like()

we don't have shape of Tensor

In [36]:
var_2dt = tf.Variable([[1,2],[2,3]])
var_2dt

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[1, 2],
       [2, 3]], dtype=int32)>

In [38]:
zl_2dt_from_var = tf.zeros_like(var_2dt)
zl_2dt_from_var

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[0, 0],
       [0, 0]], dtype=int32)>

In [39]:
zl_2dt_from_var.shape

TensorShape([2, 2])

In [41]:
zl_2dt_from_var.dtype

tf.int32

## tf.zeros_initializer()

In [43]:
def zeros_variable(shape, dtype, initializer):
    return tf.Variable(initializer(shape=shape, dtype=dtype))

In [45]:
zi_t_v = zeros_variable((2,2), tf.float32, tf.zeros_initializer())

In [46]:
zi_t_v

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[0., 0.],
       [0., 0.]], dtype=float32)>

In [50]:
zeros_variable((3,3,3), tf.bool, tf.zeros_initializer())

<tf.Variable 'Variable:0' shape=(3, 3, 3) dtype=bool, numpy=
array([[[False, False, False],
        [False, False, False],
        [False, False, False]],

       [[False, False, False],
        [False, False, False],
        [False, False, False]],

       [[False, False, False],
        [False, False, False],
        [False, False, False]]])>